spring.application.name=jpa_relationship

spring.datasource.url=jdbc:mysql://localhost:3306/user_db
spring.datasource.username=root
spring.datasource.password=ThiruGod@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Show SQL queries
spring.jpa.show-sql=true

# Format the SQL for readability
spring.jpa.properties.hibernate.format_sql=true


#- DDL auto strategies
#- create ? drops and recreates tables every startup.
#- update ? updates schema without dropping data.
#- create-drop ? creates tables at startup, drops them at shutdown.